version: '3'

services:
  proxy:
    container_name: proxy-server_container
    image: nginx
    volumes:
      - ./html:/var/www/html
      - ./templates:/etc/nginx/templates
    ports:
      - "80:80"
    depends_on:
      - pgadmin
      - teamcity
    env_file: .env
    networks:
      - server-net

volumes:
  proxy:

networks:
  server-net:
