version: '3'

services:
  dbteamcity:
    container_name: dbteamcity_container
    image: postgres
    volumes:
      - dbteamcity:/data/postgres
    ports:
      - "5433:5432"
    env_file: .env
    restart: unless-stopped

  teamcity:
    container_name: teamcity_container
    image: jetbrains/teamcity-server:latest
    volumes:
      - "/opt/teamcity/data:/data/teamcity_server/datadir"
      - "/opt/teamcity/logs:/opt/teamcity/logs"
    ports:
      - "8111:8111"
    env_file: .env
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
