version: "3.9"

services:
  postgres:
    container_name: postgres_container
    image: postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    env_file: .env
    restart: unless-stopped
    networks:
      - server-net

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    volumes:
      - pgadmin:/var/lib/pgadmin
    env_file: .env
    restart: unless-stopped
    networks:
      - server-net

volumes:
  postgres:
  pgadmin:

networks:
  server-net:
    name: server-net
    driver: bridge
