version: "3.9"

services:
  proxy:
    container_name: proxy-server_container
    image: nginx
    user: root
    volumes:
      - ./html:/var/www/html
      - ./templates:/etc/nginx/templates
      - ./nginx/var/lib/docker/volumes/mediaData/_data:/opt/media
    env_file: .env
    network_mode: host

volumes:
  proxy:
