version: '3'

services:
  proxy:
    container_name: proxy-server_container
    image: nginx
    volumes:
      - ./html:/var/www/html
      - ./templates:/etc/nginx/templates
    ports:
      - "80:80"
    links:
      - pgadmin
    env_file: .env

networks:
  proxy:
    external: true
