version: '3'

services:
  teamcity-agent:
    build: ./agents/node
    env_file: .env
    depends_on:
      - teamcity
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  db-teamcity:
    container_name: dbteamcity_container
    image: postgres
    volumes:
      - db-teamcity:/data/postgres
    ports:
      - "5433:5432"
    env_file: .env
    restart: unless-stopped

  teamcity:
    container_name: teamcity_container
    image: jetbrains/teamcity-server:latest
    user: root
    volumes:
      - "/opt/teamcity/data:/data/teamcity_server/datadir"
      - "/opt/teamcity/logs:/opt/teamcity/logs"
    ports:
      - "8111:8111"
    env_file: .env
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

volumes:
  teamcity-agent:
  db-teamcity:
  teamcity:
