version: '3'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    volumes:
      - "postgres:/data/postgres"
    ports:
      - "5432:5432"
    env_file: .env
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    volumes:
      - "pgadmin:/var/lib/pgadmin"
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    env_file: .env
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

