version: '3'

services:
  proxy:
    container_name: proxy-server_container
    image: nginx
    volumes:
      - ./html:/var/www/html
      - ./templates:/etc/nginx/templates
    ports:
      - "80:80"
    links:
      - pgadmin
    env_file: .env

  postgres:
    container_name: postgres_container
    image: postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    env_file: .env
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    env_file: .env
    restart: unless-stopped

networks:
  proxy:
    external: true

volumes:
  proxy:
  postgres:
  pgadmin:
