version: '3'

services:
  web:
    image: nginx
    volumes:
      - ./html:/var/www/html
      - ./templates:/etc/nginx/templates
    ports:
      - "80:80"
    env_file: .env

networks:
  web:
    external: true
