version: '3'

services:
  web:
    image: nginx
    volumes:
      - .nginx-configs/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    env_file: .env

networks:
  web:
    external: true
