version: "3.9"

services:
  teamcity-agent:
    container_name: teamcity-agent1_container
    image: jetbrains/teamcity-agent:2022.04.3-linux-sudo
    user: root
    env_file: .env
    volumes:
      - "./teamcity/teamcity-agent-1/opt/teamcity-agent-config:/data/teamcity_agent/conf"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./teamcity/teamcity-agent-1/opt/buildagent/work:/opt/buildagent/work"
      - "./teamcity/teamcity-agent-1/opt/buildagent/temp:/opt/buildagent/temp"
      - "./teamcity/teamcity-agent-1/opt/buildagent/tools:/opt/buildagent/tools"
      - "./teamcity/teamcity-agent-1/opt/buildagent/plugins:/opt/buildagent/plugins"
      - "./teamcity/teamcity-agent-1/opt/buildagent/system:/opt/buildagent/system"
    networks:
      - server-net

  db-teamcity:
    container_name: dbteamcity_container
    image: postgres:14
    user: root
    volumes:
      - ./db-teamcity:/data/postgres
    ports:
      - "5433:5432"
    env_file: .env
    restart: unless-stopped
    networks:
      - server-net

  teamcity:
    container_name: teamcity_container
    image: jetbrains/teamcity-server:latest
    user: root
    volumes:
      - "./teamcity/opt/teamcity_builds:/opt/teamcity_builds"
      - "./teamcity/opt/teamcity/data:/data/teamcity_server/datadir"
      - "./teamcity/opt/teamcity/logs:/opt/teamcity/logs"
    ports:
      - "8111:8111"
    depends_on:
      - db-teamcity
    env_file: .env
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      - server-net

volumes:
  teamcity-agent:
  db-teamcity:
  teamcity:

networks:
  server-net:
    name: server-net
    driver: bridge
