version: '3'

services:
  web:
    image: nginx
    volumes:
      - ./nginx-configs:/etc/nginx/templates
    ports:
      - "8080:80"
    env_file: .env

  team-city:
    image: jetbrains/teamcity-server:latest
    networks:
      - web
      - default
    volumes:
      - "/opt/teamcity/data:/data/teamcity_server/datadir"
      - "/opt/teamcity/logs:/opt/teamcity/logs"
    hostname: ${VIRTUAL_HOST}
    ports:
      - "8111"
    depends_on:
      - postgres
    env_file: .env
    labels:
      - "traefik.enable=true"
      - "traefik.backend=server"
      - "traefik.frontend.rule=Host:${VIRTUAL_HOST}"
      - "traefik.docker.network=web"
      - "traefik.port=8111"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  postgres:
    build: ./postgres
    volumes:
      - "/opt/teamcity/pg_data:/var/lib/postgresql/data"
      - "/opt/teamcity/pg_backup:/backups"
    env_file: .env
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

networks:
  web:
    external: true
